version: '3'

services:
  elk:
    image: dagman62/elk:6.7.0
    container_name: elk
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - elk_data:/var/lib/elasticsearch
      
volumes:
  elk_data:
